added tsql function and tests
datacamp/sqlwhat-ext pull request #1
Opened 2017-07-02 19:57 UTC by colinricardo

@machow wasn't sure about the 'private' class / functions, so let me know what the right way to do this is! 

Thanks :)

2017-07-02 20:02 UTC, colinricardo commented on README.md
>  ```
oops sorry I may have misunderstood this

2017-07-03 10:07 UTC, machow requested changes

2017-07-03 10:07 UTC, machow commented on sqlwhat_ext.py
> +        test_column(child, k, msg, match = 'exact')
It looks like match was changed from "any" to "exact". This is different from what's being used in the tsql course, and was changed to "any" in response to Graeme's feedback. Are we changing it back? 

Original code: https://github.com/datacamp/sqlwhat/blob/msft-check-result/sqlwhat/checks/check_result.py#L34

2017-07-03 10:07 UTC, machow commented on tests/test_check_result_tsql.py
> +from sqlwhat.Reporter import Reporter
awww yeeaahhh

2017-07-03 10:36 UTC, machow approved these changes

2017-07-03 10:40 UTC, machow commented
I changed the SCT to use match = 'any', which was what it was set for for the tsql course. Definitely let me know if it should be changed back (or we can also add a `match` argument to `check_result_mssql`, etc..).

I also modified the unit tests a little bit. They looked good, but I figured it might be useful to demonstrate another way pytest lets people run a lot of similar tests.

Once everything looks good to you let me know and I'll merge / deploy!

2017-07-03 15:11 UTC, colinricardo commented on sqlwhat_ext.py
> +        test_column(child, k, msg, match = 'exact')
@machow oops sorry, this is entirely the product of derp. It should be `'any'`.

2017-07-03 15:13 UTC, colinricardo commented on tests/test_check_result_tsql.py
> +def test_check_result_tsql_pass(sol_res, stu_res):
very cool

2017-07-03 15:14 UTC, colinricardo commented
@machow looks good, thanks! 🎉

2017-07-04 09:21 UTC, merged